name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm run lint

  test-lib:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm test:lib

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        file:
          - standard
          - typescript
          - webpack
        version:
          - ember-cli-3.28
          - ember-cli-4.4
          - ember-cli-4.8
          - ember-cli-4.12
          - ember-cli-5.4
          - ember-cli-5.8
          - ember-cli-5.12
          - ember-cli-6.4
          - ember-cli-latest
        exclude:
          - file: typescript
            version: ember-cli-3.28
          - file: typescript
            version: ember-cli-4.4
          - file: typescript
            version: ember-cli-4.8
          - file: typescript
            version: ember-cli-4.12
          - file: typescript
            version: ember-cli-5.4
          # Skipped because types are wrong. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/73848
          - file: typescript
            version: ember-cli-5.8
          # Skipped because types are wrong. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/73848
          - file: typescript
            version: ember-cli-5.12
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm vitest -t ${{matrix.version}} tests/${{ matrix.file }}.test.js
